import { readFileSync } from "node:fs";
import path from "node:path";
import type { NextConfig } from "next";

type LegacyRedirect = { source: string; destination: string; permanent: boolean };

/**
 * Redirects from the old WordPress URLs, generated by `pnpm build:redirects`.
 * Read from disk rather than imported so a missing file degrades to an empty
 * list instead of failing the build.
 */
function legacyRedirects(): LegacyRedirect[] {
  try {
    const file = path.join(process.cwd(), "data", "redirects.json");
    return JSON.parse(readFileSync(file, "utf8")) as LegacyRedirect[];
  } catch {
    return [];
  }
}

const nextConfig: NextConfig = {
  // All imagery is downloaded locally at ingest — the source origin sits
  // behind a bot-challenge and cannot be optimised remotely.
  images: {
    formats: ["image/avif", "image/webp"],
  },
  async redirects() {
    return legacyRedirects();
  },
};

export default nextConfig;
